# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres:
    container_name: vacancy_container
    build: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root_auth}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db_vacancy}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - container-network
    restart: unless-stopped

  pgadmin:
    container_name: v_admin_container
    build: ./pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - container-network
    restart: unless-stopped

networks:
  container-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
